### ISSUE TITLE
Remove `Mutex` from `StreamReader` and `StreamWriter` types

### ISSUE THREAD

**Issue by rustaceanrob** [rustaceanrob/kyoto#62]
Because the `arti-client::DataStream` is not `Sync`. Using this issue to log what is happening downstream. 

```rust
pub(crate) type StreamReader = Mutex<Box<dyn AsyncRead + Send + Unpin>>;
pub(crate) type StreamWriter = Mutex<Box<dyn AsyncWrite + Send + Unpin>>;
```

**Comment by oleonardolima** [comment]
If the issue ends up being a downside for the architecture, I don't see a problem with relying on our own patched/forked version of `arti-client` as it's an experimental feature.

**Comment by rustaceanrob** [comment]
I wouldn't want to publish a crate using a dependency from a git hash. We will just have to see what happens downstream once I get this account approved. I was only considering the feature as experimental for MSRV, but maintaining a patch and continuously rebasing would be pretty annoying. I am hopeful they will accept the patch though

**Comment by oleonardolima** [comment]
Sure, but if they take too long to accept and `arti-client` is being a downside on architecture, feel free to remove it altogether 😁.

**Comment by rustaceanrob** [comment]
I did further digging and ran the patch with making `DataStream` thread safe, but this caused panics while running the Tor example that I don't want to debug. I will live with the `Mutex`
